language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - secure: "IEmCQNLHz63zsgcaVVbbeJDZ/Ayx58iJebr5zKDUN/Cbb5MZyW8WgQ5VIn3hlnJsPZrYLx0h3PPSqOB2qLKa02VQaljC50edjSVqT3UsIyC7S+xFA0Vnz492Lf6QFjO6ZiCOqtDiY4fPjOF16nyQO46V2tx4+2W7qVuGy6QHGZw="
    - DB=mysql
  matrix:
    - MAGENTO_VERSION="magento-ce-2.0.0" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.1" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.2" INSTALL_SAMPLE_DATA=0

script:
  - composer create-project —stability=stable —no-install magento/project-community-edition Magento
  - phpunit -c phpunit_config.xml Test/Unit/