language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

matrix:
  exclude:
      env: DB=config  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0
    - php: hhvm

#script: phpunit --configuration phpunit_$DB.xml --coverage-text